/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ospedale.View;

import Data.Storage;
import Ospedale.AppContext;
import Ospedale.Controller.AppointmentController;
import Ospedale.Controller.DoctorController;
import Ospedale.Controller.HospitalizationController;
import Ospedale.Controller.NavigationController;
import Ospedale.Controller.PatientController;
import Ospedale.Controller.Utils.Response;
import Ospedale.DTO.DoctorCreateDTO;
import Ospedale.DTO.DoctorListDTO;
import Ospedale.DTO.UserOptionDTO;
import Ospedale.Model.Appointment.Appointment;
import Ospedale.Model.User.Doctor;
import Ospedale.Model.Hospitalization.Hospitalization;
import Ospedale.Model.User.Patient;
import Ospedale.Model.Specialty;
import Ospedale.Model.User.User;
import Ospedale.View.PatientView;
import Ospedale.View.BaseView;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class AdminView extends javax.swing.JFrame {
   private int x,y;
   private User user;
   private AppContext context;
    private NavigationController navigationController;
    private AppointmentController appctrl;
    private HospitalizationController hospctrl;
    private PatientController ptctrl;
    private DoctorController doctrl;
    private ArrayList<User> users;
    private ArrayList<Hospitalization> hospitalizations;
    private ArrayList<Appointment> appointments;

    public AdminView(User user,
                     AppointmentController appctrl,
                     HospitalizationController hospctrl,
                     PatientController ptctrl,
                     DoctorController doctrl) {

        initComponents();

        this.user = user;
        this.appctrl = appctrl;
        this.hospctrl = hospctrl;
        this.ptctrl = ptctrl;
        this.doctrl = doctrl;
        this.users = Storage.getInstance().getUsers();
        this.hospitalizations = Storage.getInstance().getHospitalizations();
        this.appointments = Storage.getInstance().getAppointments();
        this.navigationController = new NavigationController(user, appctrl, hospctrl, ptctrl, doctrl);
        loadSpecialtyCombo();
        loadUserCombos();

        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    public AdminView(User user, AppContext context) {
        this(user,
             context.getAppointmentController(),
             context.getHospitalizationController(),
             context.getPatientController(),
             context.getDoctorController());
        this.context = context;
        this.navigationController = new NavigationController(user, context);
        registerObservers();
    }

    public AdminView(User user) {
        initComponents();
        this.user = user;
        this.users = Storage.getInstance().getUsers();
        this.hospitalizations = Storage.getInstance().getHospitalizations();
        this.appointments = Storage.getInstance().getAppointments();
        this.navigationController = new NavigationController(user, appctrl, hospctrl, ptctrl, doctrl);
        loadSpecialtyCombo();
        loadUserCombos();
        this.setLocationRelativeTo(null);
    }

    public AdminView(User user,
                     ArrayList<User> users,
                     ArrayList<Hospitalization> hospitalizations,
                     ArrayList<Appointment> appointments) {
        initComponents();
        this.user = user;
        this.users = users;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        this.navigationController = new NavigationController(user, appctrl, hospctrl, ptctrl, doctrl);
        loadSpecialtyCombo();
        loadUserCombos();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlrMain = new Ospedale.View.Component.PanelRound();
        pnlrTitle = new Ospedale.View.Component.PanelRound();
        btnX = new javax.swing.JButton();
        lblAdminView = new javax.swing.JLabel();
        pnlrContainer = new Ospedale.View.Component.PanelRound();
        btnDoctorView = new javax.swing.JButton();
        btnPatientView = new javax.swing.JButton();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblSpecialty = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        txtLicense = new javax.swing.JTextField();
        lblAssignedOffice = new javax.swing.JLabel();
        txtAssignedOffice = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblPasswordConfirmation = new javax.swing.JLabel();
        txtPasswordConfirmation = new javax.swing.JTextField();
        cmbDoctorSpecialtyRegistration = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        sSeparator = new javax.swing.JSeparator();
        cmbDoctor = new javax.swing.JComboBox<>();
        lblDoctor = new javax.swing.JLabel();
        lblPatient = new javax.swing.JLabel();
        cmbPatient = new javax.swing.JComboBox<>();
        sSeparator2 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlrMain.setRadius(50);

        pnlrTitle.setRadius(50);
        pnlrTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlrTitleMouseDragged(evt);
            }
        });
        pnlrTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlrTitleMousePressed(evt);
            }
        });

        btnX.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnX.setText("X");
        btnX.setBorderPainted(false);
        btnX.setContentAreaFilled(false);
        btnX.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnX.setFocusable(false);
        btnX.setRequestFocusEnabled(false);
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        lblAdminView.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblAdminView.setText("ADMIN VIEW");

        javax.swing.GroupLayout pnlrTitleLayout = new javax.swing.GroupLayout(pnlrTitle);
        pnlrTitle.setLayout(pnlrTitleLayout);
        pnlrTitleLayout.setHorizontalGroup(
            pnlrTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrTitleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAdminView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnX)
                .addGap(19, 19, 19))
        );
        pnlrTitleLayout.setVerticalGroup(
            pnlrTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdminView))
        );

        btnDoctorView.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnDoctorView.setText("DOCTOR VIEW");
        btnDoctorView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorViewActionPerformed(evt);
            }
        });

        btnPatientView.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnPatientView.setText("PATIENT VIEW");
        btnPatientView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientViewActionPerformed(evt);
            }
        });

        lblFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblFirstName.setText("Firstname");

        txtFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLastName.setText("Lastname");

        txtLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblID.setText("ID");

        txtID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblSpecialty.setText("Specialty");

        lblLicense.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLicense.setText("License Number");

        txtLicense.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAssignedOffice.setText("Assigned office");

        txtAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblUser.setText("User");

        txtUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPassword.setText("Password");

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPasswordConfirmation.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPasswordConfirmation.setText("Password confirmation");

        txtPasswordConfirmation.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cmbDoctorSpecialtyRegistration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbDoctorSpecialtyRegistration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        btnSave.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        sSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cmbDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDoctor.setText("Doctor");

        lblPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatient.setText("Patient");

        cmbPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        sSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlrContainerLayout = new javax.swing.GroupLayout(pnlrContainer);
        pnlrContainer.setLayout(pnlrContainerLayout);
        pnlrContainerLayout.setHorizontalGroup(
            pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrContainerLayout.createSequentialGroup()
                .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlrContainerLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlrContainerLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlrContainerLayout.createSequentialGroup()
                                .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblSpecialty))
                                .addGap(18, 18, 18)
                                .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlrContainerLayout.createSequentialGroup()
                                        .addComponent(cmbDoctorSpecialtyRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblLicense)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlrContainerLayout.createSequentialGroup()
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(lblLastName)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblID)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlrContainerLayout.createSequentialGroup()
                                .addComponent(lblAssignedOffice)
                                .addGap(18, 18, 18)
                                .addComponent(txtAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlrContainerLayout.createSequentialGroup()
                                    .addComponent(lblUser)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlrContainerLayout.createSequentialGroup()
                                    .addComponent(lblPassword)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlrContainerLayout.createSequentialGroup()
                                    .addComponent(lblPasswordConfirmation)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDoctorView)
                            .addGroup(pnlrContainerLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cmbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlrContainerLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblDoctor)))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrContainerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(318, 318, 318)))
                .addComponent(sSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlrContainerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPatientView)
                            .addGroup(pnlrContainerLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(cmbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlrContainerLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblPatient)))
                .addGap(88, 88, 88))
            .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrContainerLayout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(sSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        pnlrContainerLayout.setVerticalGroup(
            pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrContainerLayout.createSequentialGroup()
                .addComponent(sSeparator)
                .addContainerGap())
            .addGroup(pnlrContainerLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpecialty)
                    .addComponent(cmbDoctorSpecialtyRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicense)
                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAssignedOffice)
                    .addComponent(txtAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlrContainerLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPasswordConfirmation)
                            .addComponent(txtPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlrContainerLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblDoctor)
                        .addGap(18, 18, 18)
                        .addComponent(cmbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnDoctorView)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(123, 123, 123)
                .addComponent(btnLogout)
                .addGap(38, 38, 38))
            .addGroup(pnlrContainerLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lblPatient)
                .addGap(18, 18, 18)
                .addComponent(cmbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnPatientView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlrContainerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sSeparator2)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pnlrMainLayout = new javax.swing.GroupLayout(pnlrMain);
        pnlrMain.setLayout(pnlrMainLayout);
        pnlrMainLayout.setHorizontalGroup(
            pnlrMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrMainLayout.createSequentialGroup()
                .addComponent(pnlrContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlrTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlrMainLayout.setVerticalGroup(
            pnlrMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrMainLayout.createSequentialGroup()
                .addGroup(pnlrMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlrMainLayout.createSequentialGroup()
                        .addComponent(pnlrTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 682, Short.MAX_VALUE))
                    .addGroup(pnlrMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlrContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlrMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlrMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlrTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlrTitleMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlrTitleMousePressed

    private void pnlrTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlrTitleMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pnlrTitleMouseDragged

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnXActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        DoctorCreateDTO dto = new DoctorCreateDTO(
                txtID.getText(),
                txtFirstName.getText(),
                txtLastName.getText(),
                txtUser.getText(),
                txtPassword.getText(),
                txtPasswordConfirmation.getText(),
                cmbDoctorSpecialtyRegistration.getItemAt(cmbDoctorSpecialtyRegistration.getSelectedIndex()),
                txtLicense.getText(),
                txtAssignedOffice.getText()
        );
        Response response = doctrl.createDoctor(dto, user);
        JOptionPane.showMessageDialog(null, response.getMessage());
        if (response.isSuccess()) {
            clearDoctorFields();
            loadUserCombos();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDoctorViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorViewActionPerformed
        Response response = doctrl.findDoctor(extractComboId(cmbDoctor.getItemAt(cmbDoctor.getSelectedIndex())));
        JOptionPane.showMessageDialog(null, response.getMessage());
        if (!response.isSuccess()) {
            return;
        }
        navigationController.openDoctorViewById(this, ((Number) response.getData().get("doctorId")).longValue());
    }//GEN-LAST:event_btnDoctorViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        navigationController.openLogin(this);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPatientViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientViewActionPerformed
        Response response = doctrl.findPatient(extractComboId(cmbPatient.getItemAt(cmbPatient.getSelectedIndex())));
        JOptionPane.showMessageDialog(null, response.getMessage());
        if (!response.isSuccess()) {
            return;
        }
        navigationController.openPatientViewById(this, ((Number) response.getData().get("patientId")).longValue());
    }//GEN-LAST:event_btnPatientViewActionPerformed

    private void loadUserCombos() {
        if (cmbDoctor == null || cmbPatient == null || doctrl == null) {
            return;
        }
        cmbDoctor.removeAllItems();
        cmbPatient.removeAllItems();
        cmbDoctor.addItem("Select one");
        cmbPatient.addItem("Select one");
        for (DoctorListDTO doctor : doctrl.getDoctorList()) {
            cmbDoctor.addItem(doctor.toString());
        }
        for (UserOptionDTO patient : doctrl.getPatientOptions()) {
            cmbPatient.addItem(patient.toString());
        }
    }

    private void registerObservers() {
        if (context == null) {
            return;
        }
        context.getStorage().addModelChangeListener(modelName -> {
            if ("users".equals(modelName)) {
                javax.swing.SwingUtilities.invokeLater(() -> loadUserCombos());
            }
        });
    }

    private void loadSpecialtyCombo() {
        if (cmbDoctorSpecialtyRegistration == null) {
            return;
        }
        cmbDoctorSpecialtyRegistration.removeAllItems();
        cmbDoctorSpecialtyRegistration.addItem("Select one");
        for (Specialty specialty : Specialty.values()) {
            cmbDoctorSpecialtyRegistration.addItem(specialty.name().replace("_", " "));
        }
    }

    private String extractComboId(String value) {
        int separator = value.indexOf(" - ");
        return separator < 0 ? value : value.substring(0, separator);
    }

    private void clearDoctorFields() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtID.setText("");
        cmbDoctorSpecialtyRegistration.setSelectedIndex(0);
        txtLicense.setText("");
        txtAssignedOffice.setText("");
        txtUser.setText("");
        txtPassword.setText("");
        txtPasswordConfirmation.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoctorView;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPatientView;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnX;
    private javax.swing.JComboBox<String> cmbDoctor;
    private javax.swing.JComboBox<String> cmbPatient;
    private javax.swing.JComboBox<String> cmbDoctorSpecialtyRegistration;
    private javax.swing.JLabel lblAdminView;
    private javax.swing.JLabel lblAssignedOffice;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordConfirmation;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblSpecialty;
    private javax.swing.JLabel lblUser;
    private Ospedale.View.Component.PanelRound pnlrContainer;
    private Ospedale.View.Component.PanelRound pnlrMain;
    private Ospedale.View.Component.PanelRound pnlrTitle;
    private javax.swing.JSeparator sSeparator;
    private javax.swing.JSeparator sSeparator2;
    private javax.swing.JTextField txtAssignedOffice;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordConfirmation;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
