/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ospedale.View;

import Ospedale.Model.User.Administrator;
import Ospedale.Model.Appointment;
import Ospedale.Model.AppointmentStatus;
import Ospedale.Model.User.Doctor;
import Ospedale.Model.Hospitalization;
import Ospedale.Model.HospitalizationStatus;
import Ospedale.Model.User.Patient;
import Ospedale.Model.Prescription;
import Ospedale.Model.RoomType;
import Ospedale.Model.Specialty;
import Ospedale.Model.User.User;
import Ospedale.View.AdminView;
import Ospedale.View.BaseView;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class DoctorView extends javax.swing.JFrame {

    private int x, y;
    private User user;
    private ArrayList<User> users;
    private ArrayList<Hospitalization>hospitalizations;
    private ArrayList<Appointment>appointments;
    private Doctor doctor;
    private Patient patient;
    public DoctorView(User user,Doctor doc, ArrayList<User> users,ArrayList<Hospitalization> hospitalizations,ArrayList<Appointment> appointments) {
        initComponents();
        this.user = user;
        this.users =users;
        this.doctor = doc;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        if (user instanceof Administrator)
            btnBack.setVisible(true);
        else    
            btnBack.setVisible(false);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlrMain = new Ospedale.View.Component.PanelRound();
        pnlrTitle = new Ospedale.View.Component.PanelRound();
        btnX = new javax.swing.JButton();
        lblDoctorView = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        tabMain = new javax.swing.JTabbedPane();
        pnlAppointmentsVisualization = new javax.swing.JPanel();
        rdbTotAppointments = new javax.swing.JRadioButton();
        scrInformation = new javax.swing.JScrollPane();
        tblInformation = new javax.swing.JTable();
        rdbPendingAppointments = new javax.swing.JRadioButton();
        btnLogout = new javax.swing.JButton();
        pnlHistoryAppointments = new javax.swing.JPanel();
        cmbPatient = new javax.swing.JComboBox<>();
        lblPatient = new javax.swing.JLabel();
        scrPantientInfo = new javax.swing.JScrollPane();
        tblPatientInfo = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        pnlModifyInfo = new javax.swing.JPanel();
        lblFirstname = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblSpecialty = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        txtLicense = new javax.swing.JTextField();
        lblAssignedOffice = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtAssignedOffice = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblPasswordConfirmation = new javax.swing.JLabel();
        txtPasswordConfirmation = new javax.swing.JTextField();
        cmbSpecialty = new javax.swing.JComboBox<>();
        BtnSave = new javax.swing.JButton();
        pnlRequest = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblAccept = new javax.swing.JLabel();
        cmbID = new javax.swing.JComboBox<>();
        sSeparator = new javax.swing.JSeparator();
        btnAccept = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblAppointmentReschedule = new javax.swing.JLabel();
        cmbAppointmentReschedule = new javax.swing.JComboBox<>();
        btnAcceptReschedule = new javax.swing.JButton();
        lblNewAppointment = new javax.swing.JLabel();
        txtNewAppointment = new javax.swing.JTextField();
        lblReason = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        sSeparator2 = new javax.swing.JSeparator();
        lblCompleteAppointment = new javax.swing.JLabel();
        lblAppointmentComplete = new javax.swing.JLabel();
        cmbAppointmentComplete = new javax.swing.JComboBox<>();
        lblDiagnosis = new javax.swing.JLabel();
        lblObservationsComplete = new javax.swing.JLabel();
        lblRecommendations = new javax.swing.JLabel();
        lblIndication = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();
        lblHospitalization = new javax.swing.JLabel();
        lblReasonHospitalization = new javax.swing.JLabel();
        lblDateEntry = new javax.swing.JLabel();
        txtDateEntry = new javax.swing.JTextField();
        lblEstDuration = new javax.swing.JLabel();
        txtEstDuration = new javax.swing.JTextField();
        lblObservationsHospitalization = new javax.swing.JLabel();
        scrObservationsHospitalization = new javax.swing.JScrollPane();
        txtObservationsHospitalization = new javax.swing.JTextArea();
        btnGenerate = new javax.swing.JButton();
        cmbRequests = new javax.swing.JComboBox<>();
        rdbRequests = new javax.swing.JRadioButton();
        rdbPatientID = new javax.swing.JRadioButton();
        scrDiagnosis = new javax.swing.JScrollPane();
        txtDiagnosis = new javax.swing.JTextArea();
        scrObservationsComplete = new javax.swing.JScrollPane();
        txtObservationsComplete = new javax.swing.JTextArea();
        scrTreatment = new javax.swing.JScrollPane();
        txtRecommendations = new javax.swing.JTextArea();
        scrIndication = new javax.swing.JScrollPane();
        txtIndication = new javax.swing.JTextArea();
        sSeparator3 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JButton();
        cmbPatientID = new javax.swing.JComboBox<>();
        scrReasonHospitalization = new javax.swing.JScrollPane();
        txtReasonHospitalization = new javax.swing.JTextArea();
        pnlPrescribeMedicaments = new javax.swing.JPanel();
        lblIDappointment = new javax.swing.JLabel();
        lblMedicationName = new javax.swing.JLabel();
        txtMedicationName = new javax.swing.JTextField();
        lblDose = new javax.swing.JLabel();
        txtDose = new javax.swing.JTextField();
        lblAdminRoute = new javax.swing.JLabel();
        txtAdminRoute = new javax.swing.JTextField();
        lblFrecuency = new javax.swing.JLabel();
        txtFrecuency = new javax.swing.JTextField();
        lblTreatment = new javax.swing.JLabel();
        txtTreatment = new javax.swing.JTextField();
        lblAdditionalInstructions = new javax.swing.JLabel();
        txtAdditionalInstructions = new javax.swing.JTextField();
        scrMedicine = new javax.swing.JScrollPane();
        tblMedicine = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnPrescribe = new javax.swing.JButton();
        cmbIDappointment = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlrMain.setRadius(50);

        pnlrTitle.setRadius(50);
        pnlrTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlrTitleMouseDragged(evt);
            }
        });
        pnlrTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlrTitleMousePressed(evt);
            }
        });

        btnX.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnX.setText("X");
        btnX.setBorderPainted(false);
        btnX.setContentAreaFilled(false);
        btnX.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnX.setFocusable(false);
        btnX.setRequestFocusEnabled(false);
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        lblDoctorView.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblDoctorView.setText("DOCTOR VIEW");

        btnBack.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlrTitleLayout = new javax.swing.GroupLayout(pnlrTitle);
        pnlrTitle.setLayout(pnlrTitleLayout);
        pnlrTitleLayout.setHorizontalGroup(
            pnlrTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDoctorView)
                .addGap(32, 32, 32)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnX)
                .addGap(19, 19, 19))
        );
        pnlrTitleLayout.setVerticalGroup(
            pnlrTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDoctorView, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBack))
        );

        rdbTotAppointments.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rdbTotAppointments.setText("Total appointments");
        rdbTotAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTotAppointmentsActionPerformed(evt);
            }
        });

        tblInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Patient", "Specialty", "Type", "Status"
            }
        ));
        scrInformation.setViewportView(tblInformation);

        rdbPendingAppointments.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rdbPendingAppointments.setText("Pending appointments");
        rdbPendingAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPendingAppointmentsActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAppointmentsVisualizationLayout = new javax.swing.GroupLayout(pnlAppointmentsVisualization);
        pnlAppointmentsVisualization.setLayout(pnlAppointmentsVisualizationLayout);
        pnlAppointmentsVisualizationLayout.setHorizontalGroup(
            pnlAppointmentsVisualizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAppointmentsVisualizationLayout.createSequentialGroup()
                .addGroup(pnlAppointmentsVisualizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout)
                    .addGroup(pnlAppointmentsVisualizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAppointmentsVisualizationLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(rdbTotAppointments)
                            .addGap(18, 18, 18)
                            .addComponent(rdbPendingAppointments))
                        .addGroup(pnlAppointmentsVisualizationLayout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(scrInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        pnlAppointmentsVisualizationLayout.setVerticalGroup(
            pnlAppointmentsVisualizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAppointmentsVisualizationLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlAppointmentsVisualizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbTotAppointments)
                    .addComponent(rdbPendingAppointments))
                .addGap(18, 18, 18)
                .addComponent(scrInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(23, 23, 23))
        );

        tabMain.addTab("Appointments visualization", pnlAppointmentsVisualization);

        cmbPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatient.setText("Patient");

        tblPatientInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrPantientInfo.setViewportView(tblPatientInfo);

        btnSearch.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHistoryAppointmentsLayout = new javax.swing.GroupLayout(pnlHistoryAppointments);
        pnlHistoryAppointments.setLayout(pnlHistoryAppointmentsLayout);
        pnlHistoryAppointmentsLayout.setHorizontalGroup(
            pnlHistoryAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryAppointmentsLayout.createSequentialGroup()
                .addGroup(pnlHistoryAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHistoryAppointmentsLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblPatient)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHistoryAppointmentsLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(scrPantientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHistoryAppointmentsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(601, 601, 601))
        );
        pnlHistoryAppointmentsLayout.setVerticalGroup(
            pnlHistoryAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryAppointmentsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlHistoryAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatient)
                    .addComponent(cmbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrPantientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnSearch)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        tabMain.addTab("History Appointments of a patient", pnlHistoryAppointments);

        lblFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblFirstname.setText("Firstname");

        txtFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLastName.setText("Lastname");

        txtLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblSpecialty.setText("Specialty");

        lblLicense.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLicense.setText("License Number");

        txtLicense.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAssignedOffice.setText("Assigned office");

        txtUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("User");

        txtAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password");

        lblPasswordConfirmation.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPasswordConfirmation.setText("Password confirmation");

        txtPasswordConfirmation.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cmbSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        BtnSave.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlModifyInfoLayout = new javax.swing.GroupLayout(pnlModifyInfo);
        pnlModifyInfo.setLayout(pnlModifyInfoLayout);
        pnlModifyInfoLayout.setHorizontalGroup(
            pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(lblFirstname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLastName)
                        .addGap(18, 18, 18)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSpecialty)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(lblLicense)
                        .addGap(18, 18, 18)
                        .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAssignedOffice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(lblPasswordConfirmation))
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(BtnSave))
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(txtPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        pnlModifyInfoLayout.setVerticalGroup(
            pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstname)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecialty)
                    .addComponent(cmbSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicense)
                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAssignedOffice))
                .addGap(30, 30, 30)
                .addComponent(lblUser)
                .addGap(18, 18, 18)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addGap(27, 27, 27)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPasswordConfirmation)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtnSave)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        tabMain.addTab("Modify info", pnlModifyInfo);

        lblID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblID.setText("Appointment ID");

        lblAccept.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAccept.setText("Accept medical appointment");

        cmbID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        sSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAccept.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Reschedule medical appointment");

        lblAppointmentReschedule.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentReschedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointmentReschedule.setText("Appointment");

        cmbAppointmentReschedule.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAppointmentReschedule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        btnAcceptReschedule.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAcceptReschedule.setText("Accept");
        btnAcceptReschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptRescheduleActionPerformed(evt);
            }
        });

        lblNewAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblNewAppointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewAppointment.setText("New time appointment");

        txtNewAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblReason.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReason.setText("Reason for appointment");

        txtReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        sSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblCompleteAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCompleteAppointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompleteAppointment.setText("Complete medical appointment");

        lblAppointmentComplete.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentComplete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointmentComplete.setText("Appointment");

        cmbAppointmentComplete.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAppointmentComplete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblDiagnosis.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDiagnosis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiagnosis.setText("Diagnosis");

        lblObservationsComplete.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblObservationsComplete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObservationsComplete.setText("Observations");

        lblRecommendations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRecommendations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecommendations.setText("Recommended treatment");

        lblIndication.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblIndication.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndication.setText("Follow-up indication");

        btnComplete.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        lblHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalization.setText("Hospitalization");

        lblReasonHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblReasonHospitalization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReasonHospitalization.setText("Reason for hospitalization");

        lblDateEntry.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDateEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateEntry.setText("Date of entry");

        txtDateEntry.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblEstDuration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblEstDuration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstDuration.setText("Estimated duration");

        txtEstDuration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblObservationsHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblObservationsHospitalization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObservationsHospitalization.setText("Observations");

        txtObservationsHospitalization.setColumns(20);
        txtObservationsHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtObservationsHospitalization.setRows(5);
        scrObservationsHospitalization.setViewportView(txtObservationsHospitalization);

        btnGenerate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        cmbRequests.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbRequests.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        rdbRequests.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rdbRequests.setText("Requests");

        rdbPatientID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rdbPatientID.setText("Patient ID");

        txtDiagnosis.setColumns(20);
        txtDiagnosis.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtDiagnosis.setRows(5);
        scrDiagnosis.setViewportView(txtDiagnosis);

        txtObservationsComplete.setColumns(20);
        txtObservationsComplete.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtObservationsComplete.setRows(5);
        scrObservationsComplete.setViewportView(txtObservationsComplete);

        txtRecommendations.setColumns(20);
        txtRecommendations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRecommendations.setRows(5);
        scrTreatment.setViewportView(txtRecommendations);

        txtIndication.setColumns(20);
        txtIndication.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtIndication.setRows(5);
        scrIndication.setViewportView(txtIndication);

        sSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnCancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cmbPatientID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbPatientID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        txtReasonHospitalization.setColumns(20);
        txtReasonHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtReasonHospitalization.setRows(5);
        scrReasonHospitalization.setViewportView(txtReasonHospitalization);

        javax.swing.GroupLayout pnlRequestLayout = new javax.swing.GroupLayout(pnlRequest);
        pnlRequest.setLayout(pnlRequestLayout);
        pnlRequestLayout.setHorizontalGroup(
            pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRequestLayout.createSequentialGroup()
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestLayout.createSequentialGroup()
                                        .addComponent(btnAccept)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestLayout.createSequentialGroup()
                                        .addComponent(cmbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67))))
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(sSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblAccept)
                        .addGap(22, 22, 22)))
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAppointmentReschedule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNewAppointment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlRequestLayout.createSequentialGroup()
                            .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(cmbAppointmentReschedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(txtNewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(txtReason, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(btnAcceptReschedule)))
                            .addGap(91, 91, 91))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnComplete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAppointmentComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCompleteAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlRequestLayout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(cmbAppointmentComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiagnosis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblObservationsComplete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblIndication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRecommendations, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlRequestLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(scrDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlRequestLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(scrObservationsComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlRequestLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(scrTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlRequestLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(scrIndication, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(sSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHospitalization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDateEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEstDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblObservationsHospitalization, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGenerate))
                            .addComponent(scrObservationsHospitalization, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbRequests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(rdbRequests)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestLayout.createSequentialGroup()
                                .addComponent(rdbPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestLayout.createSequentialGroup()
                                .addComponent(cmbPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReasonHospitalization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrReasonHospitalization, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        pnlRequestLayout.setVerticalGroup(
            pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sSeparator)
            .addGroup(pnlRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sSeparator2)
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblCompleteAppointment)
                        .addGap(10, 10, 10)
                        .addComponent(lblAppointmentComplete)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAppointmentComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDiagnosis)
                        .addGap(18, 18, 18)
                        .addComponent(scrDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblObservationsComplete)
                        .addGap(18, 18, 18)
                        .addComponent(scrObservationsComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRecommendations)
                        .addGap(18, 18, 18)
                        .addComponent(scrTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIndication)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrIndication, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComplete)
                        .addGap(12, 12, 12))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblAccept)
                                .addGap(18, 18, 18)
                                .addComponent(lblID)
                                .addGap(18, 18, 18)
                                .addComponent(cmbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnAccept))
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(lblAppointmentReschedule)
                                .addGap(18, 18, 18)
                                .addComponent(cmbAppointmentReschedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNewAppointment)
                                .addGap(18, 18, 18)
                                .addComponent(txtNewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblReason)
                                .addGap(18, 18, 18)
                                .addComponent(txtReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnAcceptReschedule)))
                        .addGap(18, 18, Short.MAX_VALUE))))
            .addGroup(pnlRequestLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblHospitalization)
                .addGap(18, 18, 18)
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbRequests)
                    .addComponent(rdbPatientID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRequests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblReasonHospitalization)
                .addGap(16, 16, 16)
                .addComponent(scrReasonHospitalization, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDateEntry)
                .addGap(18, 18, 18)
                .addComponent(txtDateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstDuration)
                .addGap(18, 18, 18)
                .addComponent(txtEstDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblObservationsHospitalization)
                .addGap(18, 18, 18)
                .addComponent(scrObservationsHospitalization, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerate)
                    .addComponent(btnCancel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(sSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tabMain.addTab("Request/Appointments", pnlRequest);

        lblIDappointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblIDappointment.setText("Appointment ID");

        lblMedicationName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblMedicationName.setText("Medication name");

        txtMedicationName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDose.setText("Dose");

        txtDose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAdminRoute.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAdminRoute.setText("Administration route");

        txtAdminRoute.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblFrecuency.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblFrecuency.setText("Frecuency");

        txtFrecuency.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblTreatment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblTreatment.setText("Treatment duration");

        txtTreatment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAdditionalInstructions.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAdditionalInstructions.setText("Additional instructions");

        txtAdditionalInstructions.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        tblMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Medication name", "Dose", "Administration route", "Treatment duration", "Additional instructions", "Frecuency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrMedicine.setViewportView(tblMedicine);

        btnAdd.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnPrescribe.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnPrescribe.setText("Prescribe");
        btnPrescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescribeActionPerformed(evt);
            }
        });

        cmbIDappointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbIDappointment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout pnlPrescribeMedicamentsLayout = new javax.swing.GroupLayout(pnlPrescribeMedicaments);
        pnlPrescribeMedicaments.setLayout(pnlPrescribeMedicamentsLayout);
        pnlPrescribeMedicamentsLayout.setHorizontalGroup(
            pnlPrescribeMedicamentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrescribeMedicamentsLayout.createSequentialGroup()
                .addGroup(pnlPrescribeMedicamentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrescribeMedicamentsLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(pnlPrescribeMedicamentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPrescribeMedicamentsLayout.createSequentialGroup()
                                .addGroup(pnlPrescribeMedicamentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrescribeMedicamentsLayout.createSequentialGroup()
                                        .addComponent(lblIDappointment)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbIDappointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(lblMedicationName))
                                    .addGroup(pnlPrescribeMedicamentsLayout.createSequentialGroup()
                                        .addComponent(lblTreatment)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPrescribeMedicamentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlPrescribeMedicamentsLayout.createSequentialGroup()
                                        .addComponent(lblAdditionalInstructions)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAdditionalInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFrecuency)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFrecuency, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPrescribeMedicamentsLayout.createSequentialGroup()
                                        .addComponent(txtMedicationName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDose)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDose, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblAdminRoute)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAdminRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd))))
                    .addGroup(pnlPrescribeMedicamentsLayout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(btnPrescribe)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        pnlPrescribeMedicamentsLayout.setVerticalGroup(
            pnlPrescribeMedicamentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrescribeMedicamentsLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(pnlPrescribeMedicamentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDappointment)
                    .addComponent(lblMedicationName)
                    .addComponent(txtMedicationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDose)
                    .addComponent(txtDose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminRoute)
                    .addComponent(txtAdminRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(cmbIDappointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrescribeMedicamentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTreatment)
                    .addComponent(txtTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdditionalInstructions)
                    .addComponent(txtAdditionalInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFrecuency)
                    .addComponent(txtFrecuency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(scrMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnPrescribe)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tabMain.addTab("Prescribe medications", pnlPrescribeMedicaments);

        javax.swing.GroupLayout pnlrMainLayout = new javax.swing.GroupLayout(pnlrMain);
        pnlrMain.setLayout(pnlrMainLayout);
        pnlrMainLayout.setHorizontalGroup(
            pnlrMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrMainLayout.createSequentialGroup()
                .addGroup(pnlrMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlrTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabMain))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlrMainLayout.setVerticalGroup(
            pnlrMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrMainLayout.createSequentialGroup()
                .addComponent(pnlrTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabMain))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlrMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlrMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlrTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlrTitleMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlrTitleMousePressed

    private void pnlrTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlrTitleMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pnlrTitleMouseDragged

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnXActionPerformed

    private void rdbPendingAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPendingAppointmentsActionPerformed
        // TODO add your handling code here:
        rdbTotAppointments.setSelected(false);
        Doctor d = (Doctor) user;
        DefaultTableModel model = (DefaultTableModel) tblInformation.getModel();
        model.setRowCount(0);
        for (Appointment a : d.getAppointments()) {
            if (a.getStatus().equals(AppointmentStatus.PENDING)) {
                model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getPatient().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In person" : "Virtual", a.getStatus().name()});
            }
        }
    }//GEN-LAST:event_rdbPendingAppointmentsActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        String firstname = txtFirstname.getText();
        String lastname = txtLastName.getText();
        String spec = cmbSpecialty.getItemAt(cmbSpecialty.getSelectedIndex());
        String licenseNumber = txtLicense.getText();
        String assignedOffice = txtAssignedOffice.getText();
        String username = txtUser.getText();
        String password = txtPassword.getText();
        String comPassword = txtPasswordConfirmation.getText();
        Specialty specialty = Specialty.valueOf(spec.replaceAll(" &", "").replaceAll(" ", "_"));
        if (password.equals(comPassword)) {
            for(User doc: this.users){
                if (doctor.getId() == doc.getId()) {
                    doctor.setFirstname(firstname);
                    doctor.setLastname(lastname);
                    doctor.setPassword(password);
                    doctor.setUsername(username);
                    doctor.setAssignedOffice(assignedOffice);
                    doctor.setLicenceNumber(licenseNumber);
                    doctor.setSpecialty(specialty);
                    
                }
            }
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        BaseView login = new BaseView();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminView admin = new AdminView(user,users,hospitalizations, appointments);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (rdbRequests.isSelected()) {
            for(Hospitalization hosp : this.hospitalizations){
                if (cmbRequests.getItemAt(cmbRequests.getSelectedIndex()) == hosp.getId()) {
                    hosp.setStatus(HospitalizationStatus.CANCELED);
                }
            }
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        if (rdbPatientID.isSelected()) {
            for(User user: this.users){
                if (user instanceof Patient) {
                    if (cmbPatientID.getItemAt(cmbPatientID.getSelectedIndex()).equals(user.getId())) {
                        if (this.user instanceof Administrator) {
                            String reason = txtReasonHospitalization.getText();
                            String observations = txtObservationsHospitalization.getText();
                            String entDate = txtDateEntry.getText();
                            LocalDate entryDate = LocalDate.of(Integer.parseInt(entDate.substring(0, 4)), Integer.parseInt(entDate.substring(5, 7)), Integer.parseInt(entDate.substring(8)));
                            this.hospitalizations.add(new Hospitalization("asdfasdf", (Patient)user, this.doctor, LocalDate.MAX, reason, RoomType.IMC, observations, HospitalizationStatus.ONGOING));
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Patient p = null;
        for (User u : this.users) {
            if (u.getId() == Long.parseLong(cmbPatient.getItemAt(cmbPatient.getSelectedIndex()))) {
                p = (Patient) u;
            }
        }
        
        DefaultTableModel model = (DefaultTableModel) tblPatientInfo.getModel();
        model.setRowCount(0);
        for (Appointment a : p.getAppointments()) {
            model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getDoctor().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In-person" : "Remote", a.getStatus().name()});
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void rdbTotAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTotAppointmentsActionPerformed
        // TODO add your handling code here:
        rdbPendingAppointments.setSelected(false);
        Doctor d = (Doctor) user;
        DefaultTableModel model = (DefaultTableModel) tblInformation.getModel();
        model.setRowCount(0);
        for (Appointment a : d.getAppointments()) {
            model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getPatient().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In-person" : "Remote", a.getStatus().name()});
        }
    }//GEN-LAST:event_rdbTotAppointmentsActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        String idAppointment = cmbID.getItemAt(cmbID.getSelectedIndex());
        for(Appointment apo: this.appointments){
            if(apo.getId() == idAppointment){
                apo.setStatus(AppointmentStatus.PENDING);
            }
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        String idAppointment = cmbAppointmentComplete.getItemAt(cmbAppointmentComplete.getSelectedIndex());
        String diagnosis = txtDiagnosis.getText();
        String observations = txtObservationsComplete.getText();
        String recommendedTrea = txtRecommendations.getText();
        String followUp = txtIndication.getText();
        for(Appointment apo: this.appointments){
            if(apo.getId() == idAppointment){
                apo.setStatus(AppointmentStatus.CANCELED);
                apo.setDiagnosis(diagnosis);
                apo.setFollowUp(followUp);
                apo.setRecommendedTreatment(recommendedTrea);
                apo.setObservations(observations);
            }
        }
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnPrescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescribeActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblMedicine.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnPrescribeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblMedicine.getModel();
        
        String appointmentId = cmbIDappointment.getItemAt(cmbIDappointment.getSelectedIndex());
        String medicationName = txtMedicationName.getText();
        double dose = Double.parseDouble(txtDose.getText());
        String administrationRoute = txtAdminRoute.getText();
        int tratementduration = Integer.parseInt(txtTreatment.getText());
        String aditionalIformation = txtAdditionalInstructions.getText();
        int frecuency = Integer.parseInt(txtFrecuency.getText());
        
        model.addRow(new Object[]{appointmentId, medicationName, txtDose.getText(), administrationRoute, "" + tratementduration, aditionalIformation, "" + frecuency});
        for(Appointment apo: this.appointments){
            if (apo.getId().equals(appointmentId)){
                apo.addPrescription(new Prescription(apo, medicationName, dose, administrationRoute, tratementduration, aditionalIformation, frecuency));
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAcceptRescheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptRescheduleActionPerformed
        String appointmentId = cmbAppointmentReschedule.getItemAt(cmbAppointmentReschedule.getSelectedIndex());
        Appointment appointment = null;
        for(Appointment apo: this.appointments){
            if (apo.getId().equals(appointmentId)) {
                appointment = apo;
            }
        }
        appointment.getDatetime().with(LocalTime.of(Integer.parseInt(txtNewAppointment.getText().substring(0, 2)),Integer.parseInt(txtNewAppointment.getText().substring(3))));
        String reasonChangeTime = txtReason.getText();
        appointment.setReason(reasonChangeTime);
    }//GEN-LAST:event_btnAcceptRescheduleActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAcceptReschedule;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrescribe;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnX;
    private javax.swing.JComboBox<String> cmbAppointmentComplete;
    private javax.swing.JComboBox<String> cmbAppointmentReschedule;
    private javax.swing.JComboBox<String> cmbID;
    private javax.swing.JComboBox<String> cmbIDappointment;
    private javax.swing.JComboBox<String> cmbPatient;
    private javax.swing.JComboBox<String> cmbPatientID;
    private javax.swing.JComboBox<String> cmbRequests;
    private javax.swing.JComboBox<String> cmbSpecialty;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel lblAccept;
    private javax.swing.JLabel lblAdditionalInstructions;
    private javax.swing.JLabel lblAdminRoute;
    private javax.swing.JLabel lblAppointmentComplete;
    private javax.swing.JLabel lblAppointmentReschedule;
    private javax.swing.JLabel lblAssignedOffice;
    private javax.swing.JLabel lblCompleteAppointment;
    private javax.swing.JLabel lblDateEntry;
    private javax.swing.JLabel lblDiagnosis;
    private javax.swing.JLabel lblDoctorView;
    private javax.swing.JLabel lblDose;
    private javax.swing.JLabel lblEstDuration;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblFrecuency;
    private javax.swing.JLabel lblHospitalization;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDappointment;
    private javax.swing.JLabel lblIndication;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblMedicationName;
    private javax.swing.JLabel lblNewAppointment;
    private javax.swing.JLabel lblObservationsComplete;
    private javax.swing.JLabel lblObservationsHospitalization;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordConfirmation;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblReason;
    private javax.swing.JLabel lblReasonHospitalization;
    private javax.swing.JLabel lblRecommendations;
    private javax.swing.JLabel lblSpecialty;
    private javax.swing.JLabel lblTreatment;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlAppointmentsVisualization;
    private javax.swing.JPanel pnlHistoryAppointments;
    private javax.swing.JPanel pnlModifyInfo;
    private javax.swing.JPanel pnlPrescribeMedicaments;
    private javax.swing.JPanel pnlRequest;
    private Ospedale.View.Component.PanelRound pnlrMain;
    private Ospedale.View.Component.PanelRound pnlrTitle;
    private javax.swing.JRadioButton rdbPatientID;
    private javax.swing.JRadioButton rdbPendingAppointments;
    private javax.swing.JRadioButton rdbRequests;
    private javax.swing.JRadioButton rdbTotAppointments;
    private javax.swing.JSeparator sSeparator;
    private javax.swing.JSeparator sSeparator2;
    private javax.swing.JSeparator sSeparator3;
    private javax.swing.JScrollPane scrDiagnosis;
    private javax.swing.JScrollPane scrIndication;
    private javax.swing.JScrollPane scrInformation;
    private javax.swing.JScrollPane scrMedicine;
    private javax.swing.JScrollPane scrObservationsComplete;
    private javax.swing.JScrollPane scrObservationsHospitalization;
    private javax.swing.JScrollPane scrPantientInfo;
    private javax.swing.JScrollPane scrReasonHospitalization;
    private javax.swing.JScrollPane scrTreatment;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTable tblInformation;
    private javax.swing.JTable tblMedicine;
    private javax.swing.JTable tblPatientInfo;
    private javax.swing.JTextField txtAdditionalInstructions;
    private javax.swing.JTextField txtAdminRoute;
    private javax.swing.JTextField txtAssignedOffice;
    private javax.swing.JTextField txtDateEntry;
    private javax.swing.JTextArea txtDiagnosis;
    private javax.swing.JTextField txtDose;
    private javax.swing.JTextField txtEstDuration;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtFrecuency;
    private javax.swing.JTextArea txtIndication;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtMedicationName;
    private javax.swing.JTextField txtNewAppointment;
    private javax.swing.JTextArea txtObservationsComplete;
    private javax.swing.JTextArea txtObservationsHospitalization;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordConfirmation;
    private javax.swing.JTextField txtReason;
    private javax.swing.JTextArea txtReasonHospitalization;
    private javax.swing.JTextArea txtRecommendations;
    private javax.swing.JTextField txtTreatment;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
