/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ospedale.View;

import Ospedale.AppContext;
import Ospedale.Controller.AppointmentController;
import Ospedale.Controller.DoctorController;
import Ospedale.Controller.HospitalizationController;
import Ospedale.Controller.NavigationController;
import Ospedale.Controller.PatientController;
import Ospedale.Controller.Utils.Response;
import Ospedale.DTO.AppointmentCreateDTO;
import Ospedale.DTO.AppointmentTableDTO;
import Ospedale.Model.User.Administrator;
import Ospedale.Model.Appointment;
import Ospedale.Model.AppointmentStatus;
import Ospedale.Model.User.Doctor;
import Ospedale.Model.Hospitalization;
import Ospedale.Model.User.Patient;
import Ospedale.Model.RoomType;
import Ospedale.Model.Specialty;
import Ospedale.Model.User.User;
import Ospedale.View.BaseView;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class PatientView extends javax.swing.JFrame {

    private int x, y;
    private User user;
    private AppContext context;
    private Response response;
    private NavigationController nav;
    private AppointmentController appctrl;
    private HospitalizationController hospctrl;
    private PatientController ptctrl;
    private DoctorController doctrl;

public PatientView(User user,
                   NavigationController nav,
                   AppointmentController appctrl,
                   DoctorController doctrl,
                   HospitalizationController hospctrl,
                   PatientController ptctrl) {

    initComponents();

    this.user = user;
    this.nav = nav;
    this.appctrl = appctrl;
    this.doctrl = doctrl;
    this.hospctrl = hospctrl;
    this.ptctrl = ptctrl;

    lblBack.setVisible(user instanceof Administrator);

    this.setLocationRelativeTo(null);
}

public PatientView(User user,
                   AppContext context,
                   NavigationController nav,
                   AppointmentController appctrl,
                   DoctorController doctrl,
                   HospitalizationController hospctrl,
                   PatientController ptctrl) {

    this(user, nav, appctrl, doctrl, hospctrl, ptctrl);
    this.context = context;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlrMain = new Ospedale.View.Component.PanelRound();
        pnlrTitle = new Ospedale.View.Component.PanelRound();
        btnX = new javax.swing.JButton();
        lblPatientView = new javax.swing.JLabel();
        lblBack = new javax.swing.JButton();
        tabFunctions = new javax.swing.JTabbedPane();
        pnlAppointmentHistory = new javax.swing.JPanel();
        scrContainer = new javax.swing.JScrollPane();
        tblInformation = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlModifyInfo = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblBirthdate = new javax.swing.JLabel();
        txtBirthdate = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblPasswordConfirmation = new javax.swing.JLabel();
        txtPasswordConfirmation = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        pnlRequest = new javax.swing.JPanel();
        lblRequest = new javax.swing.JLabel();
        rdbSpecialty = new javax.swing.JRadioButton();
        rdbDoctor = new javax.swing.JRadioButton();
        sSeparator = new javax.swing.JSeparator();
        lblAppointmentDate = new javax.swing.JLabel();
        txtAppointmentDate = new javax.swing.JTextField();
        txtAppointmentTime = new javax.swing.JTextField();
        lblAppointmentTime = new javax.swing.JLabel();
        lblAppointmentType = new javax.swing.JLabel();
        lblAppointmentReason = new javax.swing.JLabel();
        cmbAppointmentType = new javax.swing.JComboBox<>();
        btnCreateAppointment = new javax.swing.JButton();
        sSeparator2 = new javax.swing.JSeparator();
        lblHospitalization = new javax.swing.JLabel();
        lblHospitalizationReason = new javax.swing.JLabel();
        lblAttendingDoctor = new javax.swing.JLabel();
        cmbAttendingDoctor = new javax.swing.JComboBox<>();
        txtDateAdmission = new javax.swing.JTextField();
        lblDateAdmission = new javax.swing.JLabel();
        lblRoomType = new javax.swing.JLabel();
        cmbRoomType = new javax.swing.JComboBox<>();
        lblObservationsHospitalization = new javax.swing.JLabel();
        scrObservationsHospitalization = new javax.swing.JScrollPane();
        txtObservationsHospitalization = new javax.swing.JTextArea();
        btnCreateHospitalization = new javax.swing.JButton();
        lblCancelAppointment = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblObservationsCancel = new javax.swing.JLabel();
        scrObservationsCancel = new javax.swing.JScrollPane();
        txtObservationsCancel = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        scrHospitalizationReason = new javax.swing.JScrollPane();
        txtHospitalizationReason = new javax.swing.JTextArea();
        scrAppointmentReason = new javax.swing.JScrollPane();
        txtAppointmentReason = new javax.swing.JTextArea();
        cmbID = new javax.swing.JComboBox<>();
        cmbTypeRequest = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlrMain.setRadius(50);

        pnlrTitle.setRadius(50);
        pnlrTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlrTitleMouseDragged(evt);
            }
        });
        pnlrTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlrTitleMousePressed(evt);
            }
        });

        btnX.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnX.setText("X");
        btnX.setBorderPainted(false);
        btnX.setContentAreaFilled(false);
        btnX.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnX.setFocusable(false);
        btnX.setRequestFocusEnabled(false);
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        lblPatientView.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblPatientView.setText("PATIENT VIEW");

        lblBack.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblBack.setText("Back");
        lblBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlrTitleLayout = new javax.swing.GroupLayout(pnlrTitle);
        pnlrTitle.setLayout(pnlrTitleLayout);
        pnlrTitleLayout.setHorizontalGroup(
            pnlrTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPatientView)
                .addGap(29, 29, 29)
                .addComponent(lblBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnX)
                .addGap(19, 19, 19))
        );
        pnlrTitleLayout.setVerticalGroup(
            pnlrTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrTitleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnX))
            .addGroup(pnlrTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblPatientView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblInformation.setAutoCreateRowSorter(true);
        tblInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrContainer.setViewportView(tblInformation);

        btnRefresh.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAppointmentHistoryLayout = new javax.swing.GroupLayout(pnlAppointmentHistory);
        pnlAppointmentHistory.setLayout(pnlAppointmentHistoryLayout);
        pnlAppointmentHistoryLayout.setHorizontalGroup(
            pnlAppointmentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAppointmentHistoryLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(scrContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(pnlAppointmentHistoryLayout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(78, 78, 78))
        );
        pnlAppointmentHistoryLayout.setVerticalGroup(
            pnlAppointmentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAppointmentHistoryLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(scrContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(pnlAppointmentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnLogout))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tabFunctions.addTab("Appointment history", pnlAppointmentHistory);

        lblFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblFirstName.setText("Firstname");

        txtFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLastName.setText("Lastname");

        txtLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblBirthdate.setText("Birthdate");

        txtBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblGender.setText("Gender");

        lblEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPhone.setText("Phone");

        txtPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAddress.setText("Address");

        txtAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPassword.setText("Password");

        lblPasswordConfirmation.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPasswordConfirmation.setText("Password confirmation");

        txtPasswordConfirmation.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        btnSave.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblUser.setText("User");

        txtUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cmbGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        javax.swing.GroupLayout pnlModifyInfoLayout = new javax.swing.GroupLayout(pnlModifyInfo);
        pnlModifyInfo.setLayout(pnlModifyInfoLayout);
        pnlModifyInfoLayout.setHorizontalGroup(
            pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblFirstName)
                .addGap(18, 18, 18)
                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblLastName)
                .addGap(18, 18, 18)
                .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addComponent(lblPhone)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAddress)
                        .addGap(18, 18, 18)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBirthdate)
                        .addGap(18, 18, 18)
                        .addComponent(txtBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnSave))
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPasswordConfirmation)
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblPassword))
                    .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(lblUser)))
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlModifyInfoLayout.setVerticalGroup(
            pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyInfoLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthdate)
                    .addComponent(txtBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(lblUser)
                .addGap(18, 18, 18)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPasswordConfirmation)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSave)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tabFunctions.addTab("Modify info", pnlModifyInfo);

        lblRequest.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRequest.setText("Request medical appointment");

        rdbSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rdbSpecialty.setText("Specialty");
        rdbSpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSpecialtyActionPerformed(evt);
            }
        });

        rdbDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rdbDoctor.setText("Doctor");
        rdbDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDoctorActionPerformed(evt);
            }
        });

        sSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblAppointmentDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentDate.setText("Appointment date");

        txtAppointmentDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtAppointmentTime.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAppointmentTime.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentTime.setText("Appointment time");

        lblAppointmentType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentType.setText("Appointment type");

        lblAppointmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentReason.setText("Appointment reason");

        cmbAppointmentType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAppointmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Remote", "In-person" }));

        btnCreateAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCreateAppointment.setText("Create");
        btnCreateAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAppointmentActionPerformed(evt);
            }
        });

        sSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalization.setText("Request hospitalization");

        lblHospitalizationReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationReason.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationReason.setText("Hospitalization reason");

        lblAttendingDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAttendingDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttendingDoctor.setText("Attending doctor");

        cmbAttendingDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAttendingDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        txtDateAdmission.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDateAdmission.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDateAdmission.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateAdmission.setText("Estimated date of admission");
        lblDateAdmission.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblRoomType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRoomType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoomType.setText("Desired room type");

        cmbRoomType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblObservationsHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblObservationsHospitalization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObservationsHospitalization.setText("Observations");

        txtObservationsHospitalization.setColumns(20);
        txtObservationsHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtObservationsHospitalization.setRows(5);
        scrObservationsHospitalization.setViewportView(txtObservationsHospitalization);

        btnCreateHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCreateHospitalization.setText("Create");
        btnCreateHospitalization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHospitalizationActionPerformed(evt);
            }
        });

        lblCancelAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCancelAppointment.setText("Cancel appointment");

        lblID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblID.setText("ID appointment");

        lblObservationsCancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblObservationsCancel.setText("Observations");

        txtObservationsCancel.setColumns(20);
        txtObservationsCancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtObservationsCancel.setRows(5);
        scrObservationsCancel.setViewportView(txtObservationsCancel);

        btnCancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtHospitalizationReason.setColumns(20);
        txtHospitalizationReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtHospitalizationReason.setRows(5);
        scrHospitalizationReason.setViewportView(txtHospitalizationReason);

        txtAppointmentReason.setColumns(20);
        txtAppointmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAppointmentReason.setRows(5);
        scrAppointmentReason.setViewportView(txtAppointmentReason);

        cmbID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        cmbTypeRequest.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbTypeRequest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout pnlRequestLayout = new javax.swing.GroupLayout(pnlRequest);
        pnlRequest.setLayout(pnlRequestLayout);
        pnlRequestLayout.setHorizontalGroup(
            pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRequestLayout.createSequentialGroup()
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlRequestLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addComponent(rdbSpecialty)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdbDoctor))
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAppointmentTime)
                                        .addComponent(lblAppointmentDate)
                                        .addComponent(cmbTypeRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(lblAppointmentReason))
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(lblAppointmentType))
                                .addGroup(pnlRequestLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(cmbAppointmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pnlRequestLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(lblRequest)))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(scrAppointmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnCreateAppointment)))
                .addGap(69, 69, 69)
                .addComponent(sSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlRequestLayout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(btnCreateHospitalization))
                        .addGroup(pnlRequestLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblHospitalizationReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrHospitalizationReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(lblHospitalization, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(lblAttendingDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblObservationsHospitalization, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDateAdmission, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scrObservationsHospitalization, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRoomType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(cmbAttendingDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(txtDateAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(cmbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(sSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrObservationsCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblCancelAppointment))
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnCancel))
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblID)))
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblObservationsCancel)))
                        .addGap(49, 49, 49)))
                .addGap(81, 81, 81))
        );
        pnlRequestLayout.setVerticalGroup(
            pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sSeparator)
            .addComponent(sSeparator2)
            .addGroup(pnlRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addComponent(lblHospitalization)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(lblHospitalizationReason)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrHospitalizationReason, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAttendingDoctor)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAttendingDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDateAdmission)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDateAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblRoomType)
                        .addGap(18, 18, 18)
                        .addComponent(cmbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblObservationsHospitalization)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrObservationsHospitalization, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateHospitalization)
                        .addGap(15, 15, 15))
                    .addGroup(pnlRequestLayout.createSequentialGroup()
                        .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addComponent(lblRequest)
                                .addGap(18, 18, 18)
                                .addGroup(pnlRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdbSpecialty)
                                    .addComponent(rdbDoctor))
                                .addGap(18, 18, 18)
                                .addComponent(cmbTypeRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAppointmentDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(lblAppointmentTime)
                                .addGap(18, 18, 18)
                                .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAppointmentReason)
                                .addGap(24, 24, 24)
                                .addComponent(scrAppointmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRequestLayout.createSequentialGroup()
                                .addComponent(lblCancelAppointment)
                                .addGap(39, 39, 39)
                                .addComponent(lblID)
                                .addGap(18, 18, 18)
                                .addComponent(cmbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblObservationsCancel)
                                .addGap(18, 18, 18)
                                .addComponent(scrObservationsCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnCancel)))
                        .addGap(18, 18, 18)
                        .addComponent(lblAppointmentType)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAppointmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCreateAppointment)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabFunctions.addTab("Request/Cancel", pnlRequest);

        javax.swing.GroupLayout pnlrMainLayout = new javax.swing.GroupLayout(pnlrMain);
        pnlrMain.setLayout(pnlrMainLayout);
        pnlrMainLayout.setHorizontalGroup(
            pnlrMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlrTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabFunctions)
        );
        pnlrMainLayout.setVerticalGroup(
            pnlrMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrMainLayout.createSequentialGroup()
                .addComponent(pnlrTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabFunctions))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlrMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlrMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlrTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlrTitleMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlrTitleMousePressed

    private void pnlrTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlrTitleMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pnlrTitleMouseDragged

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnXActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        String idAppointment = cmbID.getItemAt(cmbID.getSelectedIndex());
       Response response = appctrl.cancelAppointment(idAppointment);
        JOptionPane.showMessageDialog(null, response.getMessage());
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      
        String firstname = txtFirstName.getText();
        String lastname = txtLastName.getText();
        boolean gender = cmbGender.getSelectedIndex() == 1;
        String birth = txtBirthdate.getText();
        String address = txtAddress.getText();
        long phone = Long.parseLong(txtPhone.getText());
        String email = txtEmail.getText();
        String username = txtUser.getText();
        String password = txtPassword.getText();
        String comPassword = txtPasswordConfirmation.getText();
        LocalDate birthdate = LocalDate.of(Integer.parseInt(birth.substring(0, 4)), Integer.parseInt(birth.substring(5, 7)), Integer.parseInt(birth.substring(8)));
        Response response = ptctrl.updatePatient(user.getId(), firstname, lastname, gender, birthdate, address, phone, email, username, password, comPassword);
        JOptionPane.showMessageDialog(null, response.getMessage());
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        BaseView login = context == null ? new BaseView() : new BaseView(context);
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void lblBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBackActionPerformed

    nav.openAdminView(this);

    }//GEN-LAST:event_lblBackActionPerformed

    private void rdbSpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSpecialtyActionPerformed
        if (rdbDoctor.isSelected()) {
            rdbDoctor.setSelected(false);
        }

        cmbTypeRequest.removeAllItems();

        cmbTypeRequest.addItem("Select one");
        for (Specialty spec : Specialty.values()) {
            cmbTypeRequest.addItem(spec.toString().replaceAll("_", " & "));
        }
    }//GEN-LAST:event_rdbSpecialtyActionPerformed

    private void rdbDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDoctorActionPerformed
        if (rdbSpecialty.isSelected()) {
            rdbSpecialty.setSelected(false);
        }
       cmbTypeRequest.removeAllItems();
cmbTypeRequest.addItem("Select one");

for (String name : doctrl.getDoctorNames()) {
    cmbTypeRequest.addItem(name);
}
    }//GEN-LAST:event_rdbDoctorActionPerformed

    private void btnCreateAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAppointmentActionPerformed


    AppointmentCreateDTO dto = new AppointmentCreateDTO();

    dto.patientId = user.getId();

    dto.doctorId = Long.parseLong(
        cmbTypeRequest.getItemAt(cmbTypeRequest.getSelectedIndex())
    );

    String date = txtAppointmentDate.getText();
    LocalDate d = LocalDate.of(
        Integer.parseInt(date.substring(0,4)),
        Integer.parseInt(date.substring(5,7)),
        Integer.parseInt(date.substring(8,10))
    );

    String time = txtAppointmentTime.getText();
    LocalTime t = LocalTime.of(
        Integer.parseInt(time.substring(0,2)),
        Integer.parseInt(time.substring(3,5))
    );

    dto.datetime = LocalDateTime.of(d, t);

    dto.reason = txtAppointmentReason.getText();

    dto.type = cmbAppointmentType.getSelectedIndex() == 2;

    Response response = appctrl.createAppointment(dto);

    JOptionPane.showMessageDialog(null, response.getMessage());

    }//GEN-LAST:event_btnCreateAppointmentActionPerformed


    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed


    DefaultTableModel model = (DefaultTableModel) tblInformation.getModel();
    model.setRowCount(0);

    List<AppointmentTableDTO> list =
            appctrl.getPatientAppointments(user.getId());

    for (AppointmentTableDTO dto : list) {
        model.addRow(new Object[]{
            dto.id,
            dto.datetime,
            dto.doctorName,
            dto.specialty,
            dto.type,
            dto.status
        });
    }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCreateHospitalizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHospitalizationActionPerformed
        String hospitalizationReason = txtHospitalizationReason.getText();
        long idDoctor = Long.parseLong(cmbAttendingDoctor.getItemAt(cmbAttendingDoctor.getSelectedIndex()));
        LocalDate stimateDate = LocalDate.of(Integer.parseInt(txtDateAdmission.getText().substring(0, 4)),Integer.parseInt(txtDateAdmission.getText().substring(5, 7)), Integer.parseInt(txtDateAdmission.getText().substring(8)));
        RoomType desireRoom = RoomType.valueOf(cmbRoomType.getItemAt(cmbRoomType.getSelectedIndex()).toUpperCase());
        String observations = txtObservationsHospitalization.getText();
        Response response = hospctrl.createHospitalization(user.getId(),idDoctor, stimateDate, hospitalizationReason, desireRoom, observations);
    JOptionPane.showMessageDialog(null, response.getMessage());
    }//GEN-LAST:event_btnCreateHospitalizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateAppointment;
    private javax.swing.JButton btnCreateHospitalization;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnX;
    private javax.swing.JComboBox<String> cmbAppointmentType;
    private javax.swing.JComboBox<String> cmbAttendingDoctor;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbID;
    private javax.swing.JComboBox<String> cmbRoomType;
    private javax.swing.JComboBox<String> cmbTypeRequest;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAppointmentDate;
    private javax.swing.JLabel lblAppointmentReason;
    private javax.swing.JLabel lblAppointmentTime;
    private javax.swing.JLabel lblAppointmentType;
    private javax.swing.JLabel lblAttendingDoctor;
    private javax.swing.JButton lblBack;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblCancelAppointment;
    private javax.swing.JLabel lblDateAdmission;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHospitalization;
    private javax.swing.JLabel lblHospitalizationReason;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblObservationsCancel;
    private javax.swing.JLabel lblObservationsHospitalization;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordConfirmation;
    private javax.swing.JLabel lblPatientView;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRequest;
    private javax.swing.JLabel lblRoomType;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlAppointmentHistory;
    private javax.swing.JPanel pnlModifyInfo;
    private javax.swing.JPanel pnlRequest;
    private Ospedale.View.Component.PanelRound pnlrMain;
    private Ospedale.View.Component.PanelRound pnlrTitle;
    private javax.swing.JRadioButton rdbDoctor;
    private javax.swing.JRadioButton rdbSpecialty;
    private javax.swing.JSeparator sSeparator;
    private javax.swing.JSeparator sSeparator2;
    private javax.swing.JScrollPane scrAppointmentReason;
    private javax.swing.JScrollPane scrContainer;
    private javax.swing.JScrollPane scrHospitalizationReason;
    private javax.swing.JScrollPane scrObservationsCancel;
    private javax.swing.JScrollPane scrObservationsHospitalization;
    private javax.swing.JTabbedPane tabFunctions;
    private javax.swing.JTable tblInformation;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextArea txtAppointmentReason;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtBirthdate;
    private javax.swing.JTextField txtDateAdmission;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextArea txtHospitalizationReason;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextArea txtObservationsCancel;
    private javax.swing.JTextArea txtObservationsHospitalization;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordConfirmation;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
